package ldv.shuuen.bass

import com.un4seen.bass.BASS
import com.un4seen.bass.BASSMIDI

internal actual object BassConstants {
  actual val BASS_OK: Int = BASS.BASS_OK
  actual val BASS_ERROR_INIT: Int = BASS.BASS_ERROR_INIT
  actual val BASS_CONFIG_BUFFER: Int = BASS.BASS_CONFIG_BUFFER
  actual val BASS_CONFIG_UPDATEPERIOD: Int = BASS.BASS_CONFIG_UPDATEPERIOD
  actual val BASS_CONFIG_DEV_BUFFER: Int = BASS.BASS_CONFIG_DEV_BUFFER
  actual val BASS_CONFIG_DEV_PERIOD: Int = BASS.BASS_CONFIG_DEV_PERIOD
  actual val BASS_ATTRIB_BUFFER: Int = BASS.BASS_ATTRIB_BUFFER
  actual val BASS_ATTRIB_VOL: Int = BASS.BASS_ATTRIB_VOL
  actual val BASS_ATTRIB_MIDI_SRC: Int = BASSMIDI.BASS_ATTRIB_MIDI_SRC
  actual val BASS_STREAM_DECODE: Int = BASS.BASS_STREAM_DECODE
  actual val BASS_STREAM_PRESCAN: Int = BASS.BASS_STREAM_PRESCAN
  actual val BASS_MIDI_DECAYEND: Int = BASSMIDI.BASS_MIDI_DECAYEND
  actual val BASS_CONFIG_MIDI_VOICES: Int = BASSMIDI.BASS_CONFIG_MIDI_VOICES
  actual val MIDI_EVENT_NOTE: Int = BASSMIDI.MIDI_EVENT_NOTE
  actual val MIDI_EVENT_PROGRAM: Int = BASSMIDI.MIDI_EVENT_PROGRAM
  actual val MIDI_EVENT_BANK: Int = BASSMIDI.MIDI_EVENT_BANK
  actual val MIDI_EVENT_BANK_LSB: Int = BASSMIDI.MIDI_EVENT_BANK_LSB
  actual val MIDI_EVENT_VOLUME: Int = BASSMIDI.MIDI_EVENT_VOLUME
  actual val MIDI_EVENT_EXPRESSION: Int = BASSMIDI.MIDI_EVENT_EXPRESSION
  actual val MIDI_EVENT_CUTOFF: Int = BASSMIDI.MIDI_EVENT_CUTOFF
  actual val MIDI_EVENT_FINETUNE: Int = BASSMIDI.MIDI_EVENT_FINETUNE
  actual val MIDI_EVENT_PITCH: Int = BASSMIDI.MIDI_EVENT_PITCH
  actual val MIDI_EVENT_PITCHRANGE: Int = BASSMIDI.MIDI_EVENT_PITCHRANGE
  actual val MIDI_EVENT_REVERB_LEVEL: Int = BASSMIDI.MIDI_EVENT_REVERB_LEVEL
  actual val MIDI_EVENT_CHORUS_LEVEL: Int = BASSMIDI.MIDI_EVENT_CHORUS_LEVEL
  actual val MIDI_EVENT_CHORUS_MACRO: Int = BASSMIDI.MIDI_EVENT_CHORUS_MACRO
  actual val MIDI_EVENT_SYSTEM: Int = BASSMIDI.MIDI_EVENT_SYSTEM
  actual val MIDI_EVENT_TRANSPOSE: Int = BASSMIDI.MIDI_EVENT_TRANSPOSE
  actual val MIDI_EVENT_SYSTEMEX: Int = BASSMIDI.MIDI_EVENT_SYSTEMEX
  actual val MIDI_EVENT_NOTESOFF: Int = BASSMIDI.MIDI_EVENT_NOTESOFF
  actual val MIDI_EVENT_NOTES: Int = BASSMIDI.MIDI_EVENT_NOTES

  // The Android wrapper selects memory loading via a typed ByteBuffer overload, so this filetype is
  // only needed by the JVM/JNA path; defined here to satisfy the expect declaration.
  actual val BASS_FILE_MEM: Int = 1
  actual val BASS_POS_BYTE: Int = BASS.BASS_POS_BYTE
  actual val BASS_POS_MIDI_TICK: Int = BASSMIDI.BASS_POS_MIDI_TICK
  actual val BASS_POS_FLUSH: Int = BASS.BASS_POS_FLUSH
  actual val BASS_ACTIVE_STOPPED: Int = BASS.BASS_ACTIVE_STOPPED
  actual val BASS_ACTIVE_PLAYING: Int = BASS.BASS_ACTIVE_PLAYING
  actual val BASS_ACTIVE_PAUSED: Int = BASS.BASS_ACTIVE_PAUSED
}
